version: "3"

services:

  nginx:
    restart: unless-stopped
    network_mode: host
    privileged: true
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    image: nginx:alpine
    container_name: nginx
    volumes:
      - /etc/localtime:/etc/localtime:ro

      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/cert:/etc/nginx/cert:ro

      - ./nginx/html:/etc/nginx/html:ro
      - ./nginx/logs:/etc/nginx/logs

  trojan-go:
    restart: unless-stopped
    network_mode: host
    privileged: true
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    image: p4gefau1t/trojan-go
    container_name: trojan-go
    depends_on:
      - nginx
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./nginx/cert:/etc/trojan-go/cert:ro
      - ./trojan-go:/etc/trojan-go

#  trojan:
#    restart: unless-stopped
#    network_mode: host
#    privileged: true
#    logging:
#      options:
#        max-size: "10m"
#        max-file: "3"
#    image: trojangfw/trojan
#    container_name: trojan
#    working_dir: /data
#    command: trojan config.json
#    volumes:
#      - /etc/localtime:/etc/localtime:ro
#      - ./nginx/cert:/data/cert:ro
#      - ./trojan:/data

  xray:
    restart: unless-stopped
    network_mode: host
    privileged: true
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    image: teddysun/xray
    container_name: xray
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./nginx/cert:/etc/xray/cert:ro
      - ./xray:/etc/xray

  v2ray:
    restart: unless-stopped
    network_mode: host
    privileged: true
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    image: v2fly/v2fly-core
    container_name: v2ray
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./v2ray:/etc/v2ray
