
name: pull-and-push

on:
  workflow_call:
    inputs:
      origin-image:
        required: true
        type: string
      registry:
        required: true
        type: string
    secrets:
      USERNAME:
        required: true
      PASSWORD:
        required: true
      IMAGE_NAME:
        required: true

jobs:
  pull-and-push:
    name: pull-and-push
    runs-on: ubuntu-latest
    steps:
      - name: pull-and-push
        run: curl -sL https://github.com/cc332030/docker/raw/master/script/pull-and-push.sh | sudo sh
        env:
          ORIGIN_IMAGE: ${{ inputs.origin-image }}
          REGISTRY: ${{ inputs.registry }}
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          IMAGE_NAME: ${{ secrets.IMAGE_NAME }}
